#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# lint js and vue files
NODE_OPTIONS=--max-old-space-size=4096 npx --no-install lint-staged --concurrent false

# lint only staged ruby files that still exist (not deleted)
git diff --name-only --cached | xargs -I {} sh -c 'test -f "{}" && echo "{}"' | grep '\.rb$' | xargs -I {} bundle exec rubocop --force-exclusion -a "{}" || true

# stage rubocop changes to files
git diff --name-only --cached | xargs -I {} sh -c 'test -f "{}" && git add "{}"' || true
